Repository bounswe/bounswe2022group8, pull requests merged in 2022-10, with the labels that each got.

#180 Make the initials for backend
  App/backend/README.md
  App/backend/api/__init__.py
  App/backend/api/admin.py
  App/backend/api/apps.py
  App/backend/api/migrations/__init__.py
  App/backend/api/models.py
  App/backend/api/tests.py
  App/backend/api/views.py
  App/backend/backend/__init__.py
  App/backend/backend/asgi.py
  App/backend/backend/settings.py
  App/backend/backend/urls.py
  App/backend/backend/wsgi.py
  App/backend/manage.py
  App/backend/requirements.txt
  App/backend/tests/test.py
Labels: Effort: Low, Priority: Medium, coding

#183 =DB integration with PostgreSQL completed
  App/backend/api/migrations/0001_initial.py
  App/backend/api/migrations/0002_student.py
  App/backend/api/migrations/0003_professor.py
  App/backend/api/models.py
  App/backend/backend/settings.py
Labels: Effort: Low, Priority: High, coding

#190 Feature/BE-4
  App/backend/api/admin.py
  App/backend/api/decorators.py
  App/backend/api/migrations/0001_initial.py
  App/backend/api/migrations/0002_delete_professor_delete_student_delete_teacher.py
  App/backend/api/migrations/0002_student.py
  App/backend/api/migrations/0003_professor.py
  App/backend/api/models.py
  App/backend/api/serializers.py
  App/backend/api/templates/index/index.html
  App/backend/api/templates/main/base.html
  App/backend/backend/settings/base.py
  App/backend/backend/settings/development.py
  App/backend/backend/settings/production.py
  App/backend/backend/urls.py
  App/backend/backend/views.py
  App/backend/manage.py
  App/backend/requirements.txt
Labels: approved

#189 feature/BE-5
  App/backend/Dockerfile
  App/backend/README.md
  App/backend/backend/settings/development.py
  App/backend/docker-compose.yml
  App/backend/requirements.txt
Labels: Priority: Medium, Status: review needed

#200 Feature/BE-9
  App/backend/api/migrations/0003_rename_is_active_user_user_is_level2_and_more.py
  App/backend/api/models/models.py
  App/backend/api/models/user.py
  App/backend/api/serializers/auth.py
  App/backend/api/serializers/serializers.py
  App/backend/api/tests/__init__.py
  App/backend/api/tests/test.py
  App/backend/api/tests/test_register.py
  App/backend/api/urls.py
  App/backend/api/views/auth.py
  App/backend/api/views/views.py
  App/backend/backend/settings/base.py
  App/backend/backend/urls.py
  App/backend/requirements.txt
Labels: Priority: High, Status: review needed, backend

#218 feature/FE-5
  App/frontend/.dockerignore
  App/frontend/Dockerfile
  App/frontend/Dockerfile.production
  App/frontend/nginx.conf
Labels: Priority: High, coding, frontend

#225 Last changes for deployment.
  App/backend/backend/settings/production.py
  App/frontend/Dockerfile.production
  App/frontend/src/components/LoginModal.js
  App/frontend/src/components/SignupModal.js
  App/frontend/src/layout/Sidebar.js
Labels: Effort: Medium, Priority: High, milestone
